meta_product_name: "Bike Away"
meta_title: "Bike Away: always ready for a ride!"
meta_description: "Share awesome moments with people"
meta_image: "Bikeaway.png" # should exist in `app/assets/images/`
